repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    - id: markdownlint
-   repo: local
    hooks:
    - id: cargo-fmt
      name: cargo-fmt
      entry: cargo fmt -- --check
      pass_filenames: false
      always_run: true
      language: rust
    - id: cargo-clippy
      name: cargo-clippy
      entry: cargo clippy
      pass_filenames: false
      always_run: true
      language: rust
      args:
        - --all-features
