#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

args=("$@")

root="$(dirname "${0}")"
secrets="$(mktemp)"
trap 'rm -f "${secrets}"' EXIT

"${root}/aws-lambda-secrets-wrapper-rs" > "${secrets}"

# shellcheck source=/dev/null
. "${secrets}"

rm -f "${secrets}"

exec "${args[@]}"
