name: audit-lint-bump
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  bump:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/
          key: commitizen==3.2.2

      - name: install-commitizen
        run: |
          python3 -m pip install commitizen==3.2.2

      - name: get-branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: validate-commits
        if: github.ref != 'refs/heads/main'
        run: |
          cz check --rev-range origin/main..

          echo "prerelease=--prerelease=rc" >>"${GITHUB_ENV}"
          echo "devrelease=--devrelease=${GITHUB_RUN_ID}" >>"${GITHUB_ENV}"

      - name: commitizen
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

          cz --name cz_customize bump --check-consistency --yes ${prerelease} ${devrelease}

      - name: git-push
        run: |
          REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE_REPO}" "HEAD:${GITHUB_REF#refs/heads/}" --tags
